hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"
access_control:
  enabled: true
  policies:
    - tag_query: ''
      plan: ['*']
      apply: ['user:nitinteotia6548']
